language: java
jdk:
  - oraclejdk8

# Anything after trusty doesn't have Java 8
dist: trusty

# Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
# If we don't skip it Travis runs unnecessary Gradle tasks like './gradlew assemble'
install: true

# Build commits to master, PRs to master, and release tags
script: ./scripts/travis/build.sh
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
